
site_name: Blockthon Documentation
site_description: 'Blockthon - a fast and easy Python package for generating private keys and mnemonics, converting seeds, binary, and decimals.'
site_author: 'Pymmdrza'
site_url: 'https://blockthon.gitbook.io/blockthon'
repo_url: 'https://github.com/Blockthon/Blockthon'
copyright: 'Copyright © 2023, Pymmdrza'

nav:
    - Home: 'index.md'


extra:
  social:
    - type: github
      link: https://github.com/Blockthon/Blockthon
    - type: website
      link: https://mmdrza.com
    - type: telegram
      link: https://cryptoixer.t.me
    - type: medium
      link: https://mdrza.medium.com
  meta:
    - name: keywords
      content: bitcoin, ethereum, tron, private key, mnemonic, compressed address, uncompressed address, wallet, generate hex, bytes, seed, hex

theme:
  name: readthedocs
  favicon: 'images/logo.ico'
  logo: 'images/logo.png'
  feature_tabs: true
  search_index_only: true



plugins:
  - search:
      separator: '[\s\-\.]'
